Luna::ODE_BVP< T, X > Class Template Reference
A templated object for boundary-value problems as systems of first-order ordinary differential equations.
#include <ODE_BVP.h>
Public Member Functions
ODE_BVP (Equation_1matrix< T, X > *ptr_equation, const Vector< X > &nodes, Residual< T > *ptr_left_residual, Residual< T > *ptr_right_residual)
Constructor.
virtual ~ODE_BVP ()
Destructor.
Mesh1D< T, X > & solution ()
Return a pointer to the current solution mesh.
double & tolerance ()
Access the tolerance for convergence.
int & max_iterations ()
Access the maximum number of iterations.
void set_monitor_det (bool monitor)
Set whether the determinant will be monitored.
void solve_bvp ()
Solve the boundary value problem.
std::pair< unsigned, unsigned > adapt (const double &adapt_tol)
Adapt the computational mesh.
void adapt_until (const double &adapt_tol)
Solve the system with mesh refinements or unrefinements.
template<>
std::pair< unsigned, unsigned > adapt (const double &adapt_tol)
template<>
std::pair< unsigned, unsigned > adapt (const double &adapt_tol)
template<>
void adapt_until (const double &adapt_tol)
template<>
void adapt_until (const double &adapt_tol)
Detailed Description
template<class T, class X = double>
class Luna::ODE_BVP< T, X >
A templated object for boundary-value problems as systems of first-order ordinary differential equations.
Definition at line 51 of file ODE_BVP.h.
Constructor & Destructor Documentation
ODE_BVP()
template<typename T , typename X >
Luna::ODE_BVP< T, X >::ODE_BVP (Equation_1matrix< T, X > * ptr_equation, const Vector< X > & nodes, Residual< T > * ptr_left_residual, Residual< T > * ptr_right_residual)
Constructor.
Definition at line 117 of file ODE_BVP.h.
                                             :
           MAX_ITER(20), TOL(1e-8), ptr_EQUATION(ptr_equation),
           ptr_LEFT_RESIDUAL(ptr_left_residual),
           ptr_RIGHT_RESIDUAL(ptr_right_residual),
           LAST_DET_SIGN(0), MONITOR_DET(true)
  {
    SOLUTION = Mesh1D<T, X>(nodes, ptr_EQUATION -> get_order());
    unsigned eqn_order(ptr_EQUATION -> get_order());
    unsigned left_vars(ptr_LEFT_RESIDUAL -> get_number_of_vars());
    unsigned right_vars(ptr_RIGHT_RESIDUAL -> get_number_of_vars());
    unsigned left_order(ptr_LEFT_RESIDUAL -> get_order());
    unsigned right_order(ptr_RIGHT_RESIDUAL -> get_order());
    if ((left_vars != eqn_order) || (right_vars != eqn_order) ||
         (left_order + right_order != eqn_order))
    {
     std::cout << "order " << eqn_order << std::endl;
     std::cout << "left nvars " << left_vars << std::endl;
     std::cout << "right nvars " << right_vars << std::endl;
     std::cout << "left order " << left_order << std::endl;
     std::cout << "right order " << right_order << std::endl;
     std::string problem;
     problem = "The ODE_BVP equation and boundary conditions are not well\n";
     problem += "posed. The number of variables for each boundary condition\n";
     problem += "has to be the same as the order of the equation. Also the \n";
     problem += "order of both boundary conditions has to sum to the order\n";
     problem += "of the equation.\n";
     throw Error(problem);
    }
  }
 ODE_BVP()
template<typename T , typename X >
Luna::ODE_BVP< T, X >::~ODE_BVP () [virtual]
Destructor.
Definition at line 152 of file ODE_BVP.h.
    {}
Member Function Documentation
adapt() [1/3]
template<typename T , typename X >
std::pair< unsigned, unsigned > Luna::ODE_BVP< T, X >::adapt (const double & adapt_tol)
Adapt the computational mesh.
Parameters
adapt_tol The residual tolerance at a nodal point to determine whether mesh refinements will occur
Returns
A pair of values indicating the number of refinements and unrefinements.
Definition at line 261 of file ODE_BVP.h.
References Heat_plot::N, Luna::Vector< T >::norm_inf(), and Luna::Vector< T >::push_back().
Referenced by Luna::ODE_BVP< T, X >::adapt_until().
  {
    unsigned order(ptr_EQUATION -> get_order());
    unsigned N(SOLUTION.nnodes());
    Vector<T> F_node(order, 0.0);
    Vector<T> R_node(order, 0.0);
    std::vector<bool> refine(N, false);
    std::vector<bool> unrefine(N, false);
    Vector<double> Res2(N, 0.0);
    for (std::size_t node = 1; node <= N - 2; node += 2)
    {
      // set the current solution at this node
      for (unsigned var = 0; var < order; ++var)
      {
         F_node[ var ] = SOLUTION(node, var);
      }
      // set the y-pos in the eqn
      ptr_EQUATION -> coord(0) = SOLUTION.coord(node);
      // Update the equation to the nodal position
      ptr_EQUATION -> update(F_node);
      // step size centred at the node
      X invh = 1. / (SOLUTION.coord(node + 1) - SOLUTION.coord(node - 1));
      // loop over all the variables
      Vector<T> temp(order, 0.0);
      for (unsigned var = 0; var < order; ++var)
      {
        temp[ var ] = ptr_EQUATION -> residual()[ var ] - (
                SOLUTION(node + 1, var) - SOLUTION(node - 1, var)) * invh;
      }
      Res2[ node ] = temp.norm_inf();
      if (Res2[ node ] > adapt_tol)
      {
        refine[ node ] = true;
      }
      else if (Res2[ node ] < TOL / 10.)
      {
        unrefine[ node ] = true;
      }
    }
    std::size_t no_refined(0), no_unrefined(0);
    for (std::size_t i = 0; i < refine.size(); ++i)
    {
      if (refine[ i ] == true){ no_refined++; }
      if (unrefine[ i ] == true){ no_unrefined++; }
    }
    // make a new refined/unrefined mesh
    Vector<X> nodes(SOLUTION.nodes());
    Vector<X> newX;
    newX.push_back(nodes[ 0 ]);
    for (std::size_t i = 1; i < N - 1; ++i)
    {
      if (refine[ i ])
      {
        if (!refine[ i - 1 ])
        {
          // Have not already refined to the left
          // so refine left AND right with new nodes
          X left(nodes[ i - 1 ]);
          X right(nodes[ i + 1 ]);
          X here(nodes[ i ]);
          newX.push_back((left + here) / 2.);
          newX.push_back(here);
          newX.push_back((right + here) / 2.);
        }
        else
        {
          // already left refined, so just refine right
          X right(nodes[ i + 1 ]);
          X here(nodes[ i ]);
          newX.push_back(here);
          newX.push_back((right + here) / 2.);
        }
      }
      else if (!unrefine[ i ])
      {
        newX.push_back(nodes[ i ]);
      }
    }
    newX.push_back(nodes[ N - 1 ]);
    SOLUTION.remesh(newX);
    LAST_DET_SIGN = 0;
    std::pair< unsigned, unsigned > feedback;
    feedback.first = no_refined;
    feedback.second = no_unrefined;
    return feedback;
  }
adapt() [2/3]
template<>
std::pair< unsigned, unsigned > Luna::ODE_BVP< double, cmplx >::adapt (const double & adapt_tol)
Definition at line 239 of file ODE_BVP.h.
  {
    std::string problem;
    problem = " The ODE_BVP.adapt method has been called for a problem in \n";
    problem += " the complex plane. This doesn't make sense as the path is \n";
    problem += " not geometrically defined. \n";
    throw Error(problem);
  }
adapt() [3/3]
template<>
std::pair< unsigned, unsigned > Luna::ODE_BVP< cmplx, cmplx >::adapt (const double & adapt_tol)
Definition at line 250 of file ODE_BVP.h.
  {
    std::string problem;
    problem = " The ODE_BVP.adapt method has been called for a problem in \n";
    problem += " the complex plane. This doesn't make sense as the path is \n";
    problem += " not geometrically defined. \n";
    throw Error(problem);
  }
adapt_until() [1/3]
template<typename T , typename X >
void Luna::ODE_BVP< T, X >::adapt_until (const double & adapt_tol)
Solve the system with mesh refinements or unrefinements.
Parameters
adapt_tol The residual tolerance at a nodal point to determine whether mesh refinements will occur
Definition at line 378 of file ODE_BVP.h.
References Luna::ODE_BVP< T, X >::adapt(), Luna::Vector< T >::dot(), Luna::BandedMatrix< T >::fill(), and Luna::ODE_BVP< T, X >::solve_bvp().
  {
    std::pair<unsigned, unsigned> changes;
    do {
      changes = adapt(adapt_tol);
      solve_bvp();
      std::cout << " * Adapting: " << changes.first << " " << changes.second
                << std::endl;
    }while (changes.first + changes.second != 0);
  }
adapt_until() [2/3]
template<>
void Luna::ODE_BVP< double, cmplx >::adapt_until (const double & adapt_tol)
Definition at line 358 of file ODE_BVP.h.
  {
    std::string problem;
    problem = " The ODE_BVP.adapt_until method has been called for a problem\n";
    problem += " in the complex plane. This doesn't make sense as the path\n";
    problem += " is not geometrically defined. \n";
    throw Error(problem);
  }
adapt_until() [3/3]
template<>
void Luna::ODE_BVP< cmplx, cmplx >::adapt_until (const double & adapt_tol)
Definition at line 368 of file ODE_BVP.h.
  {
    std::string problem;
    problem = " The ODE_BVP.adapt_until method has been called for a problem\n";
    problem += " in the complex plane. This doesn't make sense as the path\n";
    problem += " is not geometrically defined. \n";
    throw Error(problem);
  }
max_iterations()
template<typename T , typename X >
int & Luna::ODE_BVP< T, X >::max_iterations ()
Access the maximum number of iterations.
Returns
a pointer to the maximum number of iterations
Definition at line 170 of file ODE_BVP.h.
Referenced by main().
  {
    return MAX_ITER;
  }
set_monitor_det()
template<typename T , typename X >
void Luna::ODE_BVP< T, X >::set_monitor_det (bool monitor)
Set whether the determinant will be monitored.
Parameters
monitor The boolean value determining whether the determinant will be monitored
Definition at line 176 of file ODE_BVP.h.
Referenced by main().
  {
    MONITOR_DET = monitor;
  }
solution()
template<typename T , typename X >
Mesh1D< T, X > & Luna::ODE_BVP< T, X >::solution ()
Return a pointer to the current solution mesh.
Definition at line 158 of file ODE_BVP.h.
Referenced by main().
  {
    return SOLUTION;
  }
solve_bvp()
template<typename T , typename X >
void Luna::ODE_BVP< T, X >::solve_bvp ()
Solve the boundary value problem.
Definition at line 182 of file ODE_BVP.h.
References Luna::BandedMatrix< T >::det(), Luna::Vector< T >::norm_inf(), and Luna::BandedMatrix< T >::solve().
Referenced by Luna::ODE_BVP< T, X >::adapt_until(), and main().
  {
    unsigned order(ptr_EQUATION -> get_order());
    unsigned n(SOLUTION.nnodes());
    double max_residual(1.0);
    int counter(0);
    int det_sign(LAST_DET_SIGN);
    // Banded LHS matrix
    BandedMatrix<T> a(n * order, 2 * order - 1, 2 * order - 1);
    // RHS vector
    Vector<T> b(n * order, 0.0);
    // Loop until convergence
    do {
      ++counter;
      assemble_matrix_problem(a, b);
      //TODO actions before linear solve ?
      max_residual = b.norm_inf();
      b = a.solve(b);
      // Put the solution into the 1D mesh
      for (std::size_t var = 0; var < order; ++var)
      {
        for (std::size_t i = 0; i < n; ++i)
        {
          SOLUTION(i, var) += b[ i * order + var ];
        }
      }
    } while((max_residual > TOL) && (counter < MAX_ITER));
    if (counter >= MAX_ITER)
    {
      std::string problem("solve_bvp method error: Too many iterations");
      throw Error(problem);
    }
    if (MONITOR_DET)
    {
      T det = a.det();
      if (std::real(det) < 0) {
        det_sign = -1;
      } else {
        det_sign = 1;
      }
      if (det_sign * LAST_DET_SIGN < 0)
      {
        LAST_DET_SIGN = det_sign;
        std::string problem;
        problem = "Determinant monitor has changed signs in ODE_BVP.\n";
        problem += "Bifurcation detected.\n";
        throw Error(problem);
      }
      LAST_DET_SIGN = det_sign;
    }
  }
tolerance()
template<typename T , typename X >
double & Luna::ODE_BVP< T, X >::tolerance ()
Access the tolerance for convergence.
Returns
a pointer to the tolerance
Definition at line 164 of file ODE_BVP.h.
Referenced by main().
  {
    return TOL;
  }
The documentation for this class was generated from the following file:
include/Luna/ODE_BVP.h