Examples/Nonlinear_ODE_BVP.cpp File Reference
The equation
 (f(x)-1)f''(x) + \left( \frac{2}{x^2} - 1 \right)f'(x)^2 = 1 
 is solved subject to the boundary conditions $ f(0) = 2 $ and $ f \left(\frac{\sqrt{3}}{2} \right) = \frac{3}{2}. $ The system is solved as a set of first-order equations in the form
 \begin{pmatrix} 1 & 0 \\ 0 & f(x) - 1 \end{pmatrix} \begin{bmatrix} f(x) \\ f'(x) \end{bmatrix}' = \begin{bmatrix} f'(x) \\ 1 + \left(1 - \frac{2}{x^2} \right)f'(x)^2 \end{bmatrix}, 
 The exact solution is given by $ f(x) = 1 + \sqrt{1-x^2}. $.
#include `Luna/Core`
#include `Luna/ODE`
Classes
class Luna::nonlinear_equation
class Luna::left_BC
class Luna::right_BC
Namespaces
 Luna
Enumerations
enum { f,
fd
 }
Functions
int main ()
Detailed Description
The equation
 (f(x)-1)f''(x) + \left( \frac{2}{x^2} - 1 \right)f'(x)^2 = 1 
 is solved subject to the boundary conditions $ f(0) = 2 $ and $ f \left(\frac{\sqrt{3}}{2} \right) = \frac{3}{2}. $ The system is solved as a set of first-order equations in the form
 \begin{pmatrix} 1 & 0 \\ 0 & f(x) - 1 \end{pmatrix} \begin{bmatrix} f(x) \\ f'(x) \end{bmatrix}' = \begin{bmatrix} f'(x) \\ 1 + \left(1 - \frac{2}{x^2} \right)f'(x)^2 \end{bmatrix}, 
 The exact solution is given by $ f(x) = 1 + \sqrt{1-x^2}. $.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
f
fd
Definition at line 16 of file Nonlinear_ODE_BVP.cpp.
{ f, fd };
Function Documentation
main()
int main ()
Definition at line 71 of file Nonlinear_ODE_BVP.cpp.
References f, fd, Luna::Vector< T >::linspace(), Luna::ODE_BVP< T, X >::max_iterations(), Heat_plot::N, Luna::Mesh1D< T, X >::output(), Luna::ODE_BVP< T, X >::set_monitor_det(), Luna::Vector< T >::size(), Luna::ODE_BVP< T, X >::solution(), Luna::ODE_BVP< T, X >::solve_bvp(), Luna::ODE_BVP< T, X >::tolerance(), and Heat_plot::x.
{
  cout << "------------------- Nonlinear_ODE_BVP ------------------" << endl;
  // Setup the domain
  double left(0.0); // Left boundary
  double right(sqrt(3.0) / 2.0); // Right boundary
    std::size_t N(50); // Number of nodes
    Vector<double> nodes; // Vector of nodes (uniformly spaced)
    nodes.linspace(left, right, N);
  cout << " * The nonlinear boundary problem is solved on a uniform" << endl
       << " * grid in the domain " << left << " < x < " << right
       << " containing N = " << N << endl << " * nodal points." << endl;
  // Create instances of the equation and BCs
  nonlinear_equation equation;
  left_BC left_bc;
  right_BC right_bc;
  // Create boundary value problem
  ODE_BVP<double> ode(&equation, nodes, &left_bc, &right_bc);
  /* ----- Set the initial guess ----- */
  // f = 2 - (1/sqrt(3))x (linear fit to boundary conditions)
  double gradient(- 1.0 / sqrt(3));
    for (std::size_t j=0; j < N; ++j)
    {
        double x = nodes[ j ];
        ode.solution()(j, f) = 2.0 + gradient * x;
    ode.solution()(j, fd) = gradient;
    }
  ode.tolerance() = 1e-8;
  ode.max_iterations() = 50;
  ode.set_monitor_det(false);
  // Solve
  ode.solve_bvp();
  nodes = ode.solution().nodes();
  Mesh1D<double, double> exact_solution(nodes, 2);
  for (std::size_t j=0; j < nodes.size(); ++j)
    {
        double x = nodes[ j ];
        exact_solution(j, f) = 1.0 + sqrt(1.0 - x * x);
    exact_solution(j, fd) = - x / sqrt(1.0 - x * x);
    }
  // Output the solution data
  ode.solution().output("./DATA/ODE_BVP_numerical_solution.dat");
  exact_solution.output("./DATA/ODE_BVP_exact_solution.dat");
  cout << " * To plot the numerical solution, the exact solution " << endl
       << " * and the error between the two run:" << endl
       << "python Plotting/Nonlinear_ODE_BVP_plot.py" << endl;
  cout << "--- FINISHED ---" << endl;
}