Examples/ODE_BVP_test.cpp File Reference
TODO description / rename file.
#include `Luna/Core`
#include `Luna/ODE`
Classes
class Luna::test_equation
class Luna::left_BC
class Luna::right_BC
Namespaces
 Luna
Enumerations
enum { y,
yd
 }
Functions
int main ()
Detailed Description
TODO description / rename file.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
y
yd
Definition at line 9 of file ODE_BVP_test.cpp.
{ y, yd };
Function Documentation
main()
int main ()
Definition at line 63 of file ODE_BVP_test.cpp.
References Luna::Vector< T >::linspace(), Luna::ODE_BVP< T, X >::max_iterations(), Heat_plot::N, Luna::Mesh1D< T, X >::output(), Luna::ODE_BVP< T, X >::set_monitor_det(), Luna::Vector< T >::size(), Luna::ODE_BVP< T, X >::solution(), Luna::ODE_BVP< T, X >::solve_bvp(), Luna::ODE_BVP< T, X >::tolerance(), Heat_plot::x, y, and yd.
{
  cout << "--------------------- ODE_BVP --------------------" << endl;
  // Setup the domain
  double left(0.0); // Left boundary
  double right(M_PI / 4.0); // Right boundary
    std::size_t N(1000); // Number of nodes
    Vector<double> nodes; // Vector of nodes (uniformly spaced)
    nodes.linspace(left, right, N);
  // Create instances of the equation and BCs
  test_equation equation;
  left_BC left_bc;
  right_BC right_bc;
  // Create boundary value problem
  ODE_BVP<double> ode(&equation, nodes, &left_bc, &right_bc);
  /* ----- Set the initial guess ----- */
  // y = (48/pi)x - 2 (linear fit to boundary conditions)
  double gradient(48.0 / M_PI);
    for (std::size_t j=0; j < N; ++j)
    {
        double x = nodes[ j ];
        ode.solution()(j, y) = gradient * x - 2.0;
    ode.solution()(j, yd) = gradient;
    }
  ode.tolerance() = 1e-8;
  ode.max_iterations() = 50;
  ode.set_monitor_det(false);
  // Adaptively solve the BVP
  //ode.adapt_until(1e-7);
  cout << " Number of nodes in the solution = " << ode.solution().nnodes()
       << endl;
  nodes = ode.solution().nodes();
  Mesh1D<double, double> exact_solution(nodes, 2);
  for (std::size_t j=0; j < nodes.size(); ++j)
    {
        double x = nodes[ j ];
        exact_solution(j, y) = - 2.0 * cos(2 * x) + 10.0 * sin(2 * x);
    exact_solution(j, yd) = 4.0 * sin(2 * x) + 20.0 * cos(2 * x);
    }
  // Solve
  ode.solve_bvp();
  // Output the solution data
  ode.solution().output("./DATA/ODE_BVP_numerical_solution.dat");
  exact_solution.output("./DATA/ODE_BVP_exact_solution.dat");
  //TODO plotting instructions
  cout << "--- FINISHED ---" << endl;
}