import os.path
import glob

Import( 'env opts incdir libdir topdir libs ' )

print "----- Building Luna codes -----"

# The list of codes
rec_src = []
for root, dirs, files in os.walk( '.' ):
  for file in files:
    fqn = os.path.join( root, file )
    if '.cpp' in fqn:
      if ( '~' not in fqn ) and ( '#' not in fqn ):
        rec_src.append( fqn )

# Sort the source files for the hell of it
rec_src.sort()

# Loop through sources
for fqn in rec_src:
  filename = os.path.splitext( fqn )[0]
  env.Program( filename+'.out' , [filename+'.cpp'] , OPTS = opts, LIBS = libs)
